services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build:
      context: .
    command: /entrypoint.sh
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      FIXTURE_FILE: /app/exported_data.json
    user: "${UID:-1000}:${GID:-1000}"
  
  frontend:
    build: ../mousetube_frontendv0-5
    command: /entrypoint.sh
    volumes:
      - ../mousetube_frontendv0-5:/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - web
    env_file:
      - ../mousetube_frontendv0-5/.env
      - ../mousetube_frontendv0-5/.npm:/app/.npm
    environment:
    - NPM_CONFIG_CACHE=/app/.npm
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  mariadb_data:
